In [1]:
import numpy as np
import os
from pathlib import Path
import tensorflow as tf
import tensorflow_addons as tfa
import matplotlib.pyplot as plt
import sys

In [2]:
sys.path.append('../utils')

In [5]:
from data_preparing import ChannelData, random_rotation

In [4]:
test_path = Path('../data/test_data/')
cdata = ChannelData(path=test_path, elevation='elevation')

In [6]:
cdata.add_process(random_rotation)

In [3]:
n_samples = 4
fig, axs = plt.subplots(nrows=n_sam, ncols=n_samples, figsize=(10, 10))

for image, label in cdata1.data.take(3):
    axs[0].imshow(image)
    axs[1].imshow(label)
    plt.savefig(self.output_path / 'test_rotation.png', bbox_inches='tight')

In [7]:
range(3)

range(0, 3)

In [10]:
range(3, test_tensor.shape[-1])

range(3, 5)

In [6]:
tf.gather(test_tensor, range(3), axis=-1)

<tf.Tensor: shape=(10, 100, 100, 3), dtype=float32, numpy=
array([[[[9.67969894e-02, 5.42309880e-01, 2.12218285e-01],
         [9.95550394e-01, 8.33480239e-01, 1.16295815e-01],
         [1.68357849e-01, 3.11246872e-01, 8.50486994e-01],
         ...,
         [2.65782118e-01, 2.94860482e-01, 2.57242441e-01],
         [7.88354874e-02, 9.14592028e-01, 8.43423605e-01],
         [8.75128269e-01, 6.12044454e-01, 1.79645061e-01]],

        [[1.57148600e-01, 9.13305521e-01, 7.38757849e-02],
         [2.47694731e-01, 9.76835251e-01, 6.58690929e-03],
         [4.16314602e-01, 3.40757728e-01, 2.82221437e-01],
         ...,
         [9.68987107e-01, 1.41499519e-01, 5.24541020e-01],
         [6.77121758e-01, 9.35249686e-01, 2.08638906e-02],
         [5.97058058e-01, 1.54793262e-01, 1.57391071e-01]],

        [[1.81516528e-01, 5.95904231e-01, 4.66689348e-01],
         [2.45809436e-01, 3.14525366e-01, 6.48168683e-01],
         [5.31756878e-02, 4.17366266e-01, 8.51722360e-01],
         ...,
         [

In [13]:
t1 = tf.random.uniform(shape=(10, 10, 3), minval=0, maxval=1)
t2 = tf.random.uniform(shape=(10, 10, 1), minval=0, maxval=1)

In [15]:
tf.concat([t1, t2], -1)

<tf.Tensor: shape=(10, 10, 4), dtype=float32, numpy=
array([[[0.0587604 , 0.12754643, 0.8968291 , 0.10323155],
        [0.86703694, 0.37630415, 0.71292317, 0.8560263 ],
        [0.39672887, 0.5107013 , 0.3717903 , 0.7707652 ],
        [0.48079276, 0.45359576, 0.29256952, 0.91703665],
        [0.7902434 , 0.9169401 , 0.28108573, 0.7052361 ],
        [0.9167485 , 0.2994473 , 0.42821527, 0.8984984 ],
        [0.32482433, 0.71577835, 0.21071517, 0.9541323 ],
        [0.15331006, 0.8363286 , 0.40028656, 0.08530498],
        [0.38325143, 0.00656676, 0.26541126, 0.36438572],
        [0.93045413, 0.00747716, 0.14337444, 0.9266237 ]],

       [[0.82805526, 0.39371848, 0.6846391 , 0.06310523],
        [0.6493143 , 0.7433791 , 0.82159376, 0.49688458],
        [0.00619829, 0.90502477, 0.88169   , 0.07785439],
        [0.24039257, 0.32461357, 0.06886399, 0.38995397],
        [0.5400109 , 0.8874103 , 0.4083383 , 0.39527535],
        [0.64379513, 0.8511015 , 0.4754455 , 0.3412702 ],
        [0.907383

In [11]:
process = tf.image.flip_left_right

In [16]:
from inspect import getfullargspec, get

In [13]:
args = getfullargspec(process)

In [14]:
args

FullArgSpec(args=[], varargs='args', varkw='kwargs', defaults=None, kwonlyargs=[], kwonlydefaults=None, annotations={})

In [15]:
process

<function tensorflow.python.ops.image_ops_impl.flip_left_right(image)>

In [17]:
getcallargs(process)

{'args': (), 'kwargs': {}}